# Generated by Django 5.2.11 on 2026-06-23 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delete_course_plugin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deletedcourserecord',
            name='keep_instructors',
        ),
    ]
